version: '3.2'

services:
  users:
    build: ./users
    ports:
      - '${USERS_PORT}:${USERS_PORT}'
    volumes:
      - './users:/usr/src/app'
    restart: always
    depends_on:
      - users_db

  users_db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ${USERS_MYSQL_DATABASE}
      MYSQL_USER: ${USERS_MYSQL_DATABASE_USER}
      MYSQL_PASSWORD: ${USERS_MYSQL_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${USERS_MYSQL_DATABASE_ROOT_PASSWORD}
    volumes:
      - ./usersDb:/var/lib/mysql
    ports:
      - '${USERS_MYSQL_DATABASE_PORT}:${USERS_MYSQL_DATABASE_PORT}'

  products:
    build: ./products
    ports:
      - '${PRODUCTS_PORT}:${PRODUCTS_PORT}'
    volumes:
      - './products:/usr/src/app'
    restart: always

  client:
    build: ./client
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    volumes:
      - './client:/usr/src/app'
    links:
      - users
      - products
    restart: always
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '${RABBITMQ_PORT_ONE}:${RABBITMQ_PORT_ONE}'
      - '${RABBITMQ_PORT_TWO}:${RABBITMQ_PORT_TWO}'
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
