version: "3.2"

services:
  admin:
    build: ./admin
    ports:
      - "${ADMIN_PORT}:${ADMIN_PORT}"
    volumes:
      - "./admin:/usr/src/app"
    restart: always
    depends_on:
      - admin_db

  admin_db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ${ADMIN_MYSQL_DATABASE}
      MYSQL_USER: ${ADMIN_MYSQL_DATABASE_USER}
      MYSQL_PASSWORD: ${ADMIN_MYSQL_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ADMIN_MYSQL_DATABASE_ROOT_PASSWORD}
    volumes:
      - ./adminDb:/var/lib/mysql
    ports:
      - "${ADMIN_MYSQL_DATABASE_PORT}:${ADMIN_MYSQL_DATABASE_PORT}"

  main:
    build: ./main
    ports:
      - "${MAIN_PORT}:${MAIN_PORT}"
    volumes:
      - "./main:/usr/src/app"
    restart: always

  client:
    build: ./client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - "./client:/usr/src/app"
    links:
      - admin
      - main
    restart: always
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
